# Generated by Django 4.2.4 on 2023-11-29 07:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_remove_userprofile_user_delete_customer_and_more"),
    ]

    operations = []
