# Generated by Django 4.2.4 on 2023-11-29 07:17

import django
from django.db import migrations
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_auto_20231129_1300"),
    ]

    operations = [
          migrations.AddField(
        model_name='deliveryaddress',
        name='user',
        field=models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE,
            to=settings.AUTH_USER_MODEL,

        ),
    ),
    ]
