# Generated by Django 4.2.4 on 2023-12-01 03:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_order_orderitem_order_products_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="products",
            new_name="items",
        ),
    ]
